name: my_awesome_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  firebase_core: ^3.7.0 
  firebase_auth: ^5.3.2
  firebase_database: ^11.1.5
  cloud_firestore: ^5.4.5
  firebase_data_connect: ^0.1.2
  path_provider: ^2.1.5
  flutter_html: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  
  assets: 
    - assets/example_json.json