// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0h9I5lOfnmEe9eEpdLXWqry2vstxRqjg',
    appId: '1:257463114401:web:ff8fb77ac38ed8130ceee0',
    messagingSenderId: '257463114401',
    projectId: 'ipes-survey',
    authDomain: 'ipes-survey.firebaseapp.com',
    storageBucket: 'ipes-survey.firebasestorage.app',
    measurementId: 'G-TV79B2334V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnfZbPPFEzissEz9r3ceR2bNnV_HqHy8c',
    appId: '1:257463114401:android:9d165c20ba152fc70ceee0',
    messagingSenderId: '257463114401',
    projectId: 'ipes-survey',
    storageBucket: 'ipes-survey.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs1Q9KJgow85usa9BCeLrtyiRiHyEv7xo',
    appId: '1:257463114401:ios:65986edb4d4633450ceee0',
    messagingSenderId: '257463114401',
    projectId: 'ipes-survey',
    storageBucket: 'ipes-survey.firebasestorage.app',
    iosBundleId: 'com.example.myAwesomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs1Q9KJgow85usa9BCeLrtyiRiHyEv7xo',
    appId: '1:257463114401:ios:65986edb4d4633450ceee0',
    messagingSenderId: '257463114401',
    projectId: 'ipes-survey',
    storageBucket: 'ipes-survey.firebasestorage.app',
    iosBundleId: 'com.example.myAwesomeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0h9I5lOfnmEe9eEpdLXWqry2vstxRqjg',
    appId: '1:257463114401:web:bd61a417bc5015820ceee0',
    messagingSenderId: '257463114401',
    projectId: 'ipes-survey',
    authDomain: 'ipes-survey.firebaseapp.com',
    storageBucket: 'ipes-survey.firebasestorage.app',
    measurementId: 'G-EQ4C9DMLVE',
  );
}
